### ISSUE TITLE
Explain TestKit + IDE integration

### ISSUE THREAD

**Issue by oehme** [gradle-guides/testing-gradle-plugins#3]
TestKit invoked from the IDE only works correctly if you either:

- activate "Delegate build to Gradle" in IntelliJ or
- run `gradle assembe` on every change

A lot of users, including Gradle engineers have stumbled over this. We should point this out prominently, probably also in the user guide chapter about TestKit.

**Comment by bmuschko** [comment]
I will send a separate PR for Gradle core. We already state part of the instructions here:

> When executing the functional tests from an IDE, there are extra considerations. Namely, the classpath manifest file points to the class files etc. generated by Gradle and not the IDE. This means that after making a change to the source of the code under test, the source must be recompiled by Gradle. Similarly, if the effective classpath of the code under test changes, the manifest must be regenerated. In either case, executing the testClasses task of the build will ensure that things are up to date.
